<div class="notice">
    <br/>
    <br/>
    <h3>Thank you for using one of my FREE extensions. Please consider one of my premium extensions.</h3>
    <div class="container" style="border: 1px solid black; padding: 5px;">
    <div class="product-img-box" style="width: 310px; float:left;">
        <a href="http://www.proxiblue.com.au/premium-modules/magento-dynamic-category-products.html" title="Magento Dynamic Category Products" class="product-image">
            <div class="hover-box">
                <img src="http://www.proxiblue.com.au/media/catalog/product/cache/1/small_image/300x/040ec09b1e35df139433887a97daa66f/d/y/dyncatprod_new.png" alt="Magento Dynamic Category Products">
            </div>
        </a>
    </div>
        <p style="width: 80%; float:right;">Stop wasting your valuable time manually assigning products to categories. Eliminate human error. Assign correct products to categories, and never have a product that is not assigned to a category. Using simple to use rules, you can automate the entire product to category assignment process. Spend your valuable time on other aspects of your business.</p>
    </div>
    <br/>
</div>